function neurons = thp_get_extra_neurons()

data = {
  
'BKNR_SSSA_sc.mat'    'BKNR0000'    'patch'    ...
-Inf    Inf    ...
{'spike1-double' 'spike3-double' } ...
'Rimlig latenstid, men aktiveras f?re trigger. Too large background oscillations' ...
'patch2'

'BMNR_SSSA_sc.mat'    'BMNR0000'    'patch'    ...
-Inf    Inf    ...
{'spike1-double' 'spike2-double' } ...
'Delat afferentinput?' ...
'patch2'

'DGNR_sc.mat'    'DGNR0005'    'patch'    ...
0    840    ...
{'spike2-double' 'spike3-double' } ...
'Asymmetriskt PSTH ?' ...
 ''
};

neurons(size(data, 1)) = ScPairedSpThPoints();

for i=1:length(neurons)
  
  neurons (i) = ScPairedSpThPoints(...
    'experiment_filename',  data{i, 1}, ...
    'file_tag',             data{i, 2}, ...
    'signal_tag',           data{i, 3}, ...
    'tmin',                 data{i, 4}, ...
    'tmax',                 data{i, 5}, ...
    'template_tag',         data{i, 6}, ...
    'comment',              data{i, 7}  ...
    );
  neurons(i).protocol_signal_tag = data{i, 8};
  
end

end


