function plot_single_limit(obj, index)

h_lower = plot(obj.h_axes, obj.x(index), obj.y_lower(index), ...
  'Marker', 's', 'Color', obj.color, 'MarkerSize', 12, 'LineWidth', 2, ...
  'UIContextMenu', create_ui_context_menu(obj, index));

h_upper = plot(obj.h_axes, obj.x(index), obj.y_upper(index), ...
  'Marker', 's', 'Color', obj.color, 'MarkerSize', 12, 'LineWidth', 2, ...
  'UIContextMenu', create_ui_context_menu(obj, index));

h_bar = plot(obj.h_axes, ...
  obj.x(index)*[1 1], [obj.y_lower(index) obj.y_upper(index)], ...
  'Color', obj.color, 'LineWidth', 2, ...
  'UIContextMenu', create_ui_context_menu(obj, index));

grouped_objects = [h_lower h_upper h_bar];

set(h_lower, 'ButtonDownFcn', ...
  @(src, ~) drag_object(obj, ...
  DefineThresholdGraphicObjects.LOWER_BOUND, src, grouped_objects, index));

set(h_upper, 'ButtonDownFcn', ...
  @(src, ~) drag_object(obj, ...
  DefineThresholdGraphicObjects.UPPER_BOUND, src, grouped_objects, index));

obj.all_objects = add_to_list(obj.all_objects, h_lower);
obj.all_objects = add_to_list(obj.all_objects, h_upper);
obj.all_objects = add_to_list(obj.all_objects, h_bar);

update_background_callbacks(obj);

end
