function val = get_hand_labels()

val = {
  'palm position x'
  'palm position y'
  'palm position z'
  'pitch (degrees)'
  'roll(degrees)'
  'yaw(degrees)'
  'arm direction x'
  'arm direction y'
  'arm direction z'
  'wrist position x'
  'wrist position y'
  'wrist position y'
  'elbow position x'
  'elbow position y'
  'elbow position z'
  'thumb metacarpal joint x'
  'thumb metacarpal joint y'
  'thumb metacarpal joint z'
  'thumb proximal joint x'
  'thumb proximal joint y'
  'thumb proximal joint z'
  'thumb intermediate joint x'
  'thumb intermediate joint y'
  'thumb intermediate joint z'
  'thumb distal joint x'
  'thumb distal joint y'
  'thumb distal joint z'
  'thumb fingertip x'
  'thumb fingertip y'
  'thumb fingertip z'
  'indexfinger metacarpal joint x'
  'indexfinger metacarpal joint y'
  'indexfinger metacarpal joint z'
  'indexfinger proximal joint x'
  'indexfinger proximal joint y'
  'indexfinger proximal joint z'
  'indexfinger intermediate joint x'
  'indexfinger intermediate joint y'
  'indexfinger intermediate joint z'
  'indexfinger distal joint x'
  'indexfinger distal joint y'
  'indexfinger distal joint z'
  'indexfinger fingertip x'
  'indexfinger fingertip y'
  'indexfinger fingertip z'
  'middlefinger metacarpal joint x'
  'middlefinger metacarpal joint y'
  'middlefinger metacarpal joint z'
  'middlefinger proximal joint x'
  'middlefinger proximal joint y'
  'middlefinger proximal joint z'
  'middlefinger intermediate joint x'
  'middlefinger intermediate joint y'
  'middlefinger intermediate joint z'
  'middlefinger distal joint x'
  'middlefinger distal joint y'
  'middlefinger distal joint z'
  'middlefinger fingertip x'
  'middlefinger fingertip y'
  'middlefinger fingertip z'
  'ringfinger metacarpal joint x'
  'ringfinger metacarpal joint y'
  'ringfinger metacarpal joint z'
  'ringfinger proximal joint x'
  'ringfinger proximal joint y'
  'ringfinger proximal joint z'
  'ringfinger intermediate joint x'
  'ringfinger intermediate joint y'
  'ringfinger intermediate joint z'
  'ringfinger distal joint x'
  'ringfinger distal joint y'
  'ringfinger distal joint z'
  'ringfinger fingertip x'
  'ringfinger fingertip y'
  'ringfinger fingertip z'
  'pinky metacarpal joint x'
  'pinky metacarpal joint y'
  'pinky metacarpal joint z'
  'pinky proximal joint x'
  'pinky proximal joint y'
  'pinky proximal joint z'
  'pinky intermediate joint x'
  'pinky intermediate joint y'
  'pinky intermediate joint z'
  'pinky distal joint x'
  'pinky distal joint y'
  'pinky distal joint z'
  'pinky fingertip x'
  'pinky fingertip y'
  'pinky fingertip z'};

end